language: php

php:
  - 7.1

sudo: required

services:
  - docker

before_install:
  - docker pull edamov/pushok-docker

script:
  - docker run --name=php7.1 -e TRAVIS=true -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}" -d -v /home/travis/build/semyonchetvertnyh/laravel-apn-notification-channel:/home/laravel-apn-notification-channel edamov/pushok-docker tail -f /dev/null
  - docker exec -t php7.1 /bin/sh -c "cd /home/laravel-apn-notification-channel && php /composer.phar update ${COMPOSER_FLAGS} --no-interaction --prefer-dist && /home/laravel-apn-notification-channel/vendor/bin/phpunit  --coverage-text --coverage-clover=coverage.clover"

#after_script:
#  - docker exec -t php7.1 /bin/sh -c "cd /home/laravel-apn-notification-channel && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover"


