language: php

php:
  - 7.0
#  - 7.1
#  - 7.2
#  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get install php7.0-curl php7.0-gmp
  - echo "extension = curl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = gmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
